version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci

  pre_build:
    commands:
      - echo Running lint...
      - npm run lint

  build:
    commands:
      - echo Build started on `date`
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "dist/**/*"
    - "appspec.yml"
    - "deploy-scripts/**/*"

cache:
  paths:
    - node_modules/**/*
